In [1]:
import numpy as np
import pandas as pd

from sklearn.datasets import fetch_california_housing
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix
data = fetch_california_housing(as_frame=True)
df = data.frame

X = df.drop(columns="MedHouseVal")
y = df["MedHouseVal"]
y_class = pd.qcut(y, q=3, labels=[0, 1, 2])

X_train, X_test, y_train, y_test = train_test_split(
    X, y_class, test_size=0.25, random_state=42
)
dtc = DecisionTreeClassifier(max_depth=4, random_state=42)
dtc.fit(X_train, y_train)

dt_pred = dtc.predict(X_test)

print("\nDecision Tree Results")
print("Accuracy:", accuracy_score(y_test, dt_pred))
print("Confusion Matrix:\n", confusion_matrix(y_test, dt_pred))
print("Classification Report:\n", classification_report(y_test, dt_pred))

rfc = RandomForestClassifier(n_estimators=200, random_state=42)
rfc.fit(X_train, y_train)

rf_pred = rfc.predict(X_test)

print("\nRandom Forest Results")
print("Accuracy:", accuracy_score(y_test, rf_pred))
print("Confusion Matrix:\n", confusion_matrix(y_test, rf_pred))
print("Classification Report:\n", classification_report(y_test, rf_pred))


Decision Tree Results
Accuracy: 0.6734496124031008
Confusion Matrix:
 [[1314  341   71]
 [ 456  932  326]
 [ 180  311 1229]]
Classification Report:
               precision    recall  f1-score   support

           0       0.67      0.76      0.71      1726
           1       0.59      0.54      0.57      1714
           2       0.76      0.71      0.73      1720

    accuracy                           0.67      5160
   macro avg       0.67      0.67      0.67      5160
weighted avg       0.67      0.67      0.67      5160


Random Forest Results
Accuracy: 0.811046511627907
Confusion Matrix:
 [[1493  214   19]
 [ 221 1265  228]
 [  35  258 1427]]
Classification Report:
               precision    recall  f1-score   support

           0       0.85      0.87      0.86      1726
           1       0.73      0.74      0.73      1714
           2       0.85      0.83      0.84      1720

    accuracy                           0.81      5160
   macro avg       0.81      0.81      0.81     